PREFIX mso: <http://linkeddata.uni-muenster.de/ontology/mso#>
PREFIX chord: <http://purl.org/ontology/chord/>
PREFIX note: <http://purl.org/ontology/chord/note/>


SELECT ?score ?measure WHERE {
	?score mso:hasScorePart ?part .
	?part mso:hasMeasure ?measure . 
	?measure1 mso:hasNoteSet ?noteset1 .
	?noteset1 mso:hasNote ?note1 .
	?note1 chord:natural note:D .
	?noteset1 mso:hasDuration ?duration1 .
	?duration1 a mso:Half .	
	?noteset1 mso:nextNoteSet ?noteset2 .
	?noteset2 mso:hasNote ?note2.
	?note2 chord:natural note:A .
	?noteset2 mso:hasDuration ?duration2 .
	?duration2 a mso:Half .	
	?noteset2 mso:nextNoteSet ?noteset3 .
	?noteset3 mso:hasNote ?note3.
	?note3 chord:natural note:F .
	?noteset3 mso:hasDuration ?duration3 .
	?duration3 a mso:Half .
	?noteset3 mso:nextNoteSet ?noteset4 .
	?noteset4 mso:hasNote ?note4 .
	?note4 chord:natural note:D .
	?noteset3 mso:hasDuration ?duration4 .
	?duration4 a mso:Half .
	?noteset4 mso:nextNoteSet ?noteset5 .
	?noteset5 mso:hasNote ?note5 .
	?note5 chord:natural note:C .
    ?note5 chord:modifier chord:sharp .
	?noteset5 mso:hasDuration ?duration5 .
	?duration5 a mso:Half .	
	?noteset5 mso:nextNoteSet ?noteset6 .
	?noteset6 mso:hasNote ?note6 .
	?note6 chord:natural note:D .
	?noteset6 mso:hasDuration ?duration6 .
	?duration6 a mso:Quarter .	
	?noteset6 mso:nextNoteSet ?noteset7 .
	?noteset7 mso:hasNote ?note7 .
	?note7 chord:natural note:E .
	?noteset7 mso:hasDuration ?duration7 .
	?duration7 a mso:Quarter .	
	
	?measure1 mso:nextMeasure ?measure2 .
	?measure2 mso:nextMeasure ?measure3 .
	?measure2 mso:hasNoteSet ?noteset3 .
	?measure2 mso:hasNoteSet ?noteset4 .
	?measure3 mso:hasNoteSet ?noteset5 .
	?measure3 mso:hasNoteSet ?noteset6 .
	?measure3 mso:hasNoteSet ?noteset7 .
	
} 