PREFIX mso: <http://linkeddata.uni-muenster.de/ontology/mso#>
PREFIX chord: <http://purl.org/ontology/chord/>
PREFIX note: <http://purl.org/ontology/chord/note/>


SELECT ?score ?measure1 WHERE {
	?score mso:hasScorePart ?part .
	?part mso:hasMeasure ?measure1 .    
    
	?measure1 mso:hasNoteSet ?noteset1 .
    ?measure1 mso:hasNoteSet ?noteset2 .
	?noteset1 mso:hasNote ?note1 .    
	?note1 chord:natural note:F .
	?noteset1 mso:hasDuration ?duration1 .
	?duration1 a mso:Quarter .	
	?noteset1 mso:nextNoteSet ?noteset2 .
	?noteset2 mso:hasNote ?note2.
	?note2 chord:natural note:D .	
	?noteset2 mso:hasDuration ?duration2 .
	?duration2 a mso:Eighth .
    ?measure1 mso:nextMeasure ?measure2 .    

	?measure2 mso:hasNoteSet ?noteset3 .
    ?measure2 mso:hasNoteSet ?noteset4 .
	?noteset3 mso:hasNote ?note3 .
	?note3 chord:natural note:D .
	?noteset3 mso:hasDuration ?duration3 .
	?duration3 a mso:Half .	
	?noteset3 mso:nextNoteSet ?noteset4 .
	?noteset4 mso:hasNote ?note4.
	?note4 chord:natural note:D .	
	?noteset4 mso:hasDuration ?duration4 .
	?duration4 a mso:Eighth .
} 